SRC_DIR = src
MY_DIR = ./\
	graphprint/\
	asm/\


SRCS_ASM = $(wildcard $(addsuffix *.S, $(addprefix ${SRC_DIR}/, ${MY_DIR})/)) 
SRCS_C = $(wildcard $(addsuffix *.c, $(addprefix ${SRC_DIR}/, ${MY_DIR})/))


include ../common.mk
